/**
 * Post PR Review Comments Action
 * PostJSAction that:
 * 1. Reads AI review results from outputs/response.md
 * 2. Posts review summary as PR comment
 * 3. Posts review results to Jira ticket
 * 4. Updates ticket status based on review outcome
 * 5. Adds labels to indicate review completion
 */

const { LABELS, STATUSES } = require('./config.js');

/**
 * Parse review recommendation from response
 * Looks for APPROVE/REQUEST CHANGES/BLOCK in the response
 *
 * @param {string} response - Review response text
 * @returns {string} Recommendation: APPROVE, REQUEST_CHANGES, or BLOCK
 */
function parseRecommendation(response) {
    const upper = response.toUpperCase();

    // Look for final recommendation section
    if (upper.indexOf('FINAL RECOMMENDATION') !== -1 || upper.indexOf('RECOMMENDATION') !== -1) {
        if (upper.indexOf('BLOCK') !== -1) {
            return 'BLOCK';
        }
        if (upper.indexOf('REQUEST CHANGES') !== -1 || upper.indexOf('REQUEST_CHANGES') !== -1) {
            return 'REQUEST_CHANGES';
        }
        if (upper.indexOf('APPROVE') !== -1) {
            return 'APPROVE';
        }
    }

    // Fallback: look anywhere in response
    if (upper.indexOf('BLOCK') !== -1) {
        return 'BLOCK';
    }
    if (upper.indexOf('REQUEST CHANGES') !== -1) {
        return 'REQUEST_CHANGES';
    }
    if (upper.indexOf('APPROVE') !== -1) {
        return 'APPROVE';
    }

    // Default to request changes if unclear
    return 'REQUEST_CHANGES';
}

/**
 * Count issues in review response
 *
 * @param {string} response - Review response text
 * @returns {Object} Counts of blocking, important, and suggestion issues
 */
function countIssues(response) {
    const counts = {
        blocking: 0,
        important: 0,
        suggestions: 0
    };

    // Count blocking issues (🚨 or BLOCKING)
    const blockingMatches = response.match(/🚨|BLOCKING/gi) || [];
    counts.blocking = blockingMatches.length;

    // Count important issues (⚠️ or IMPORTANT)
    const importantMatches = response.match(/⚠️|IMPORTANT/gi) || [];
    counts.important = importantMatches.length;

    // Count suggestions (💡 or SUGGESTION)
    const suggestionMatches = response.match(/💡|SUGGESTION/gi) || [];
    counts.suggestions = suggestionMatches.length;

    return counts;
}

/**
 * Extract summary section from review
 *
 * @param {string} response - Review response text
 * @returns {string} Summary section or first 500 chars
 */
function extractSummary(response) {
    // Try to extract summary section
    const summaryMatch = response.match(/##\s*📊\s*Summary\s*\n([\s\S]*?)(?=\n##|\n---|\n$)/i);
    if (summaryMatch && summaryMatch[1]) {
        return summaryMatch[1].trim();
    }

    // Fallback: first paragraph or 500 chars
    const firstPara = response.split('\n\n')[0];
    return firstPara.length > 500 ? firstPara.substring(0, 500) + '...' : firstPara;
}

/**
 * Post review comment to GitHub PR
 *
 * @param {number} prNumber - PR number
 * @param {string} reviewContent - Review content
 * @param {string} recommendation - APPROVE/REQUEST_CHANGES/BLOCK
 */
function postReviewToPR(prNumber, reviewContent, recommendation) {
    try {
        console.log('Posting review to PR #' + prNumber);

        // Prepare review comment
        let comment = '## 🤖 Automated Code Review\n\n';
        comment += reviewContent + '\n\n';
        comment += '---\n';
        comment += '*Generated by AI Code Reviewer*\n';

        // Post as PR comment
        cli_execute_command({
            command: 'gh pr comment ' + prNumber + ' --body "' + comment.replace(/"/g, '\\"').replace(/\n/g, '\\n') + '"'
        });

        console.log('✅ Posted review comment to PR #' + prNumber);

        // Note: We can't use gh pr review --approve/--request-changes in headless mode
        // So we just post a comment and let humans make the final decision

    } catch (error) {
        console.error('Failed to post review to PR:', error);
        // Non-fatal - continue with Jira update
    }
}

/**
 * Post review results to Jira ticket
 *
 * @param {string} ticketKey - Ticket key
 * @param {string} reviewContent - Review content
 * @param {string} recommendation - Review recommendation
 * @param {Object} issueCounts - Counts of issues
 * @param {string} prUrl - PR URL
 */
function postReviewToJira(ticketKey, reviewContent, recommendation, issueCounts, prUrl) {
    try {
        let comment = 'h2. 🔍 Automated PR Review Completed\n\n';

        // Add recommendation badge
        if (recommendation === 'APPROVE') {
            comment += '{panel:bgColor=#E3FCEF|borderColor=#00875A}✅ *APPROVED* - Ready to merge{panel}\n\n';
        } else if (recommendation === 'BLOCK') {
            comment += '{panel:bgColor=#FFEBE6|borderColor=#DE350B}🚨 *BLOCKED* - Critical issues must be fixed{panel}\n\n';
        } else {
            comment += '{panel:bgColor=#FFF7E6|borderColor=#FF991F}⚠️ *CHANGES REQUESTED* - Issues found that should be addressed{panel}\n\n';
        }

        // Add issue summary
        comment += 'h3. Issue Summary\n';
        comment += '* 🚨 Blocking Issues: *' + issueCounts.blocking + '*\n';
        comment += '* ⚠️ Important Issues: *' + issueCounts.important + '*\n';
        comment += '* 💡 Suggestions: *' + issueCounts.suggestions + '*\n\n';

        if (prUrl) {
            comment += 'h3. Pull Request\n';
            comment += '[View PR on GitHub|' + prUrl + ']\n\n';
        }

        // Add full review content
        comment += 'h3. Detailed Review\n\n';
        comment += reviewContent + '\n\n';

        comment += '---\n';
        comment += '_Generated by AI Code Reviewer with focus on security, code quality, and OOP principles_';

        jira_post_comment({
            key: ticketKey,
            comment: comment
        });

        console.log('✅ Posted review results to Jira ticket', ticketKey);

    } catch (error) {
        console.error('Failed to post review to Jira:', error);
    }
}

/**
 * Update ticket status based on review outcome
 *
 * @param {string} ticketKey - Ticket key
 * @param {string} recommendation - Review recommendation
 */
function updateTicketStatus(ticketKey, recommendation) {
    try {
        if (recommendation === 'APPROVE') {
            // Move to Ready for QA or Done depending on workflow
            // For now keep in In Review - human can move it forward
            console.log('Review approved - ticket remains in In Review for human decision');
        } else if (recommendation === 'BLOCK') {
            // Move back to In Development for fixes
            try {
                jira_move_to_status({
                    key: ticketKey,
                    statusName: STATUSES.IN_DEVELOPMENT
                });
                console.log('Moved ticket back to In Development due to blocking issues');
            } catch (statusError) {
                console.warn('Could not move ticket to In Development:', statusError);
            }
        } else {
            // REQUEST_CHANGES - keep in In Review
            console.log('Changes requested - ticket remains in In Review');
        }

    } catch (error) {
        console.error('Failed to update ticket status:', error);
    }
}

/**
 * Main action function
 * Posts review results and updates ticket
 *
 * @param {Object} params - Parameters from Teammate job
 * @param {Object} params.ticket - Jira ticket object
 * @param {string} params.response - Review response from AI
 * @returns {Object} Result object
 */
function action(params) {
    try {
        const ticketKey = params.ticket.key;
        const reviewResponse = params.response || '';

        console.log('=== Processing PR review results for', ticketKey, '===');

        if (!reviewResponse || !reviewResponse.trim()) {
            console.error('No review response received');
            return {
                success: false,
                error: 'No review content generated'
            };
        }

        // Parse review results
        const recommendation = parseRecommendation(reviewResponse);
        const issueCounts = countIssues(reviewResponse);

        console.log('Review recommendation:', recommendation);
        console.log('Issue counts:', JSON.stringify(issueCounts));

        // Try to extract PR info from input folder
        let prNumber = null;
        let prUrl = null;

        try {
            const inputFolder = params.inputFolderPath || ('input/' + ticketKey);
            const prInfo = file_read({
                path: inputFolder + '/pr_info.md'
            });

            // Extract PR number and URL from pr_info.md
            const numberMatch = prInfo.match(/\*PR #\*:\s*(\d+)/);
            const urlMatch = prInfo.match(/\*URL\*:\s*(https:\/\/[^\s]+)/);

            if (numberMatch) {
                prNumber = parseInt(numberMatch[1], 10);
            }
            if (urlMatch) {
                prUrl = urlMatch[1];
            }

        } catch (error) {
            console.warn('Could not read PR info from input folder:', error);
        }

        // Post review to GitHub PR (if we have PR number)
        if (prNumber) {
            postReviewToPR(prNumber, reviewResponse, recommendation);
        } else {
            console.warn('No PR number found - skipping GitHub comment');
        }

        // Post review to Jira ticket
        postReviewToJira(ticketKey, reviewResponse, recommendation, issueCounts, prUrl);

        // Update ticket status based on recommendation
        updateTicketStatus(ticketKey, recommendation);

        // Add review label
        try {
            jira_add_label({
                key: ticketKey,
                label: LABELS.AI_PR_REVIEWED
            });
        } catch (error) {
            console.warn('Failed to add ai_pr_reviewed label:', error);
        }

        // Remove WIP label if present
        const wipLabel = params.metadata && params.metadata.contextId
            ? params.metadata.contextId + '_wip'
            : 'pr_review_wip';

        try {
            jira_remove_label({
                key: ticketKey,
                label: wipLabel
            });
            console.log('Removed WIP label:', wipLabel);
        } catch (error) {
            console.warn('Failed to remove WIP label:', error);
        }

        // Assign back to initiator
        try {
            if (params.initiator) {
                jira_assign_ticket_to({
                    key: ticketKey,
                    accountId: params.initiator
                });
                console.log('Assigned ticket back to initiator');
            }
        } catch (error) {
            console.warn('Failed to assign ticket:', error);
        }

        console.log('✅ PR review workflow completed successfully');

        return {
            success: true,
            message: 'PR review completed with recommendation: ' + recommendation,
            recommendation: recommendation,
            issueCounts: issueCounts
        };

    } catch (error) {
        console.error('❌ Error in postPRReviewComments:', error);

        // Try to post error to Jira
        try {
            if (params && params.ticket && params.ticket.key) {
                jira_post_comment({
                    key: params.ticket.key,
                    comment: 'h3. ❌ PR Review Error\n\n' +
                        '{code}' + error.toString() + '{code}\n\n' +
                        'Please check the workflow logs for details.'
                });
            }
        } catch (commentError) {
            console.error('Failed to post error comment:', commentError);
        }

        return {
            success: false,
            error: error.toString()
        };
    }
}

// Export action function
module.exports = { action };
